build:
  script:
    - npm install --registry=https://registry.npm.taobao.org
    - npm run build
    - sudo rm -rf /var/www/vue/static && sudo rm /var/www/vue/index.html
    - sudo mv dist/* /var/www/vue